import { int, mysqlEnum, mysqlTable, text, timestamp, decimal, varchar } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", { id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull() });
export const categories = mysqlTable("bakery_categories", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 120 }).notNull(), slug: varchar("slug", { length: 140 }).notNull().unique(), active: int("active").default(1).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const products = mysqlTable("bakery_products", { id: int("id").autoincrement().primaryKey(), categoryId: int("categoryId"), name: varchar("name", { length: 160 }).notNull(), description: text("description").notNull(), imageUrl: text("imageUrl"), price: decimal("price", { precision: 10, scale: 2 }).notNull(), active: int("active").default(1).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const productOptions = mysqlTable("bakery_product_options", { id: int("id").autoincrement().primaryKey(), productId: int("productId").notNull(), type: mysqlEnum("type", ["size", "flavor", "filling", "customization"]).notNull(), name: varchar("name", { length: 120 }).notNull(), priceDelta: decimal("priceDelta", { precision: 10, scale: 2 }).default("0").notNull(), active: int("active").default(1).notNull() });
export const ingredients = mysqlTable("bakery_ingredients", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 140 }).notNull(), unit: varchar("unit", { length: 20 }).notNull(), currentQuantity: decimal("currentQuantity", { precision: 12, scale: 3 }).default("0").notNull(), minimumQuantity: decimal("minimumQuantity", { precision: 12, scale: 3 }).default("0").notNull(), costPerUnit: decimal("costPerUnit", { precision: 10, scale: 2 }).default("0").notNull(), active: int("active").default(1).notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const recipes = mysqlTable("bakery_recipes", { id: int("id").autoincrement().primaryKey(), productId: int("productId").notNull(), yieldQuantity: decimal("yieldQuantity", { precision: 12, scale: 3 }).default("1").notNull(), active: int("active").default(1).notNull() });
export const recipeItems = mysqlTable("bakery_recipe_items", { id: int("id").autoincrement().primaryKey(), recipeId: int("recipeId").notNull(), ingredientId: int("ingredientId").notNull(), quantity: decimal("quantity", { precision: 12, scale: 3 }).notNull() });
export const orders = mysqlTable("bakery_orders", { id: int("id").autoincrement().primaryKey(), trackingCode: varchar("trackingCode", { length: 32 }).unique(), userId: int("userId"), customerName: varchar("customerName", { length: 160 }).notNull(), customerPhone: varchar("customerPhone", { length: 32 }).notNull(), customerEmail: varchar("customerEmail", { length: 320 }), fulfillment: mysqlEnum("fulfillment", ["pickup", "delivery"]).notNull(), deliveryAddress: text("deliveryAddress"), scheduledAt: timestamp("scheduledAt").notNull(), status: mysqlEnum("status", ["received", "in_production", "ready", "out_for_delivery", "delivered", "cancelled"]).default("received").notNull(), paymentMethod: mysqlEnum("paymentMethod", ["pix", "card", "cash"]).notNull(), subtotal: decimal("subtotal", { precision: 10, scale: 2 }).notNull(), deliveryFee: decimal("deliveryFee", { precision: 10, scale: 2 }).default("0").notNull(), total: decimal("total", { precision: 10, scale: 2 }).notNull(), notes: text("notes"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const orderItems = mysqlTable("bakery_order_items", { id: int("id").autoincrement().primaryKey(), orderId: int("orderId").notNull(), productId: int("productId").notNull(), productName: varchar("productName", { length: 160 }).notNull(), quantity: int("quantity").notNull(), unitPrice: decimal("unitPrice", { precision: 10, scale: 2 }).notNull(), options: text("options"), notes: text("notes") });
export const payments = mysqlTable("bakery_payments", { id: int("id").autoincrement().primaryKey(), orderId: int("orderId").notNull(), method: mysqlEnum("method", ["pix", "card", "cash"]).notNull(), status: mysqlEnum("status", ["pending", "paid", "refunded"]).default("pending").notNull(), amount: decimal("amount", { precision: 10, scale: 2 }).notNull(), paidAt: timestamp("paidAt") });
export const productionTasks = mysqlTable("bakery_production_tasks", { id: int("id").autoincrement().primaryKey(), orderId: int("orderId").notNull(), scheduledAt: timestamp("scheduledAt").notNull(), priority: mysqlEnum("priority", ["normal", "high"]).default("normal").notNull(), notes: text("notes"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const stockMovements = mysqlTable("bakery_stock_movements", { id: int("id").autoincrement().primaryKey(), ingredientId: int("ingredientId").notNull(), type: mysqlEnum("type", ["in", "out", "adjustment"]).notNull(), quantity: decimal("quantity", { precision: 12, scale: 3 }).notNull(), reason: varchar("reason", { length: 180 }).notNull(), orderId: int("orderId"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert; export type Category = typeof categories.$inferSelect; export type Product = typeof products.$inferSelect; export type ProductOption = typeof productOptions.$inferSelect; export type Ingredient = typeof ingredients.$inferSelect; export type Recipe = typeof recipes.$inferSelect; export type RecipeItem = typeof recipeItems.$inferSelect; export type Order = typeof orders.$inferSelect; export type OrderItem = typeof orderItems.$inferSelect; export type Payment = typeof payments.$inferSelect; export type StockMovement = typeof stockMovements.$inferSelect; export type ProductionTask = typeof productionTasks.$inferSelect;
export const legacyRecords = mysqlTable("records", { id: int("id").autoincrement().primaryKey(), title: varchar("title", { length: 160 }).notNull(), category: varchar("category", { length: 120 }).notNull(), description: text("description").notNull(), status: mysqlEnum("status", ["active", "archived"]).default("active").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
